### ISSUE TITLE
pretty should output arrays on multiple lines

### ISSUE THREAD

**Issue by svnpenn** [tidwall/jj#12]
proper JQ example:

~~~sh
$ jq '.foxtrot[].golf' hotel.json
"india"
"juliet"
"kilo"
~~~

bad JJ example:

~~~sh
$ jj -n -p -i hotel.json 'foxtrot.#.golf'
["india", "juliet", "kilo"]
~~~

**Comment by svnpenn** [comment]
@tidwall I am happy with JJ returning valid JSON. I also agree that JQ should
return valid JSON - however I am in bad situation because:

1. JQ returns arrays on multiple lines, but not as valid JSON
2. JJ returns valid JSON, but array on single line

The program I end up going with with ideally:

1. return valid JSON
2. return arrays on multiple lines, either as the default or with some option

Currently it seems neither program is a complete solution.

**Comment by tidwall** [comment]
This may sound nuts but you could:
```
jj -i hotel.json 'foxtrot.#.golf' | jq .[]
```

**Comment by svnpenn** [comment]
and ideal solution would be a single program

**Comment by tidwall** [comment]
Update JJ and try this:

```
jj -l -i hotel.json 'foxtrot.#.golf'
```

**Comment by svnpenn** [comment]
This command:

~~~sh
jj -l -n -i hotel.json 'foxtrot.#.golf'
~~~

puts output on multiple lines, but is no longer valid JSON. I am happy with the
result, but I will let you decide if this is acceptable - thanks

**Comment by tidwall** [comment]
> puts output on multiple lines, but is no longer valid JSON.

Correct. It can be either multiple lines or valid json. Not both. The `-l` option outputs multiple lines. Otherwise it's a valid json array.

**Comment by svnpenn** [comment]
again I am happy with current result, but it seems JJ should be able to solve
both problems. JQ can solve both this way:

~~~sh
$ jq '[.foxtrot[].golf]' hotel.json
[
  "india",
  "juliet",
  "kilo"
]
~~~

**Comment by tidwall** [comment]
Ok. I'm closing this issue now.
