### ISSUE TITLE
output result have "%" tail ?   

### ISSUE THREAD

**Issue by KISSMonX** [tidwall/jj#5]
MacOS, iTerm2

![image](https://user-images.githubusercontent.com/2876745/34291807-067b718a-e739-11e7-816d-e138a3f9d280.png)

**Comment by tidwall** [comment]
The percent sign is not from jj. It’s something that zsh adds to break up an unterminated line. This makes the prompt always start on its own line.

https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol

**Comment by KISSMonX** [comment]
Thank you.

**Comment by tidwall** [comment]
You're welcome :)
